### PR TITLE
Close  #192: Sealed programs

### LINKED ISSUE #192: Sealed programs
Add a way to seal programs.

### PR DESCRIPTION
**Pull request by pankratov**
New opcode for sealed program creation was added. Sealed programs are  immutable.

### CODE REVIEW

**Comment by fomkin** [comment]
4. Don't forget to generate docs for asm.

**Comment by pankratov** [comment]
4. I thought it is the part of a release process...

**Comment by pankratov** [comment]
1. Ok. 
How is it supposed to be? I am going to do it in the following way now. It will be new opcode `SEAL` which will get the existing program address from the top of the stack. It will make existing program sealed.  It will be no way to UNseal the sealed program. Is it right?

**Comment by pankratov** [comment]
2. What do you mean by the `interface`? It will be new opcode in the bytecode and it will be keyword in out assembler.

**Comment by fomkin** [comment]
1. SEAL is coorect. UNSEAL is not required.
2. CLI

**Comment by pankratov** [comment]
3. Yes. You right.

**Comment by pankratov** [comment]
> 2. CLI

Got it

**Comment by fomkin** [comment]
4. Yes, it should, but currently docs are hosted on GitHub and should be generated and committed manually.

**Comment by pankratov** [comment]
Now it is opcode SEAL which make a program sealed. Also there is a comman in CLI `pravda broadcast seal --address ffeeaa...` . I've added two definitions into the Glossary  - _Stored program_ and _Sealed program_. The bug with the program address checking in CLI update was fixed.

**Comment by fomkin** [comment]
LGTM 👍

**Pull request merged**
